services:

  odoo:
    image: odoo:18.0-20241209@sha256:d2a4f769fa8ed83cf5004bcd1bb3c2d412019a4c8cc7425994dcb87b6e617bbd
    container_name: odoo-app
    hostname: odoo-app
    restart: on-failure
    ports:
      - "8069:8069"
    user: root:root
    volumes:
      - ${APP_DATA_DIR}/data/odoo:/var/lib/odoo
    depends_on:
      - db

  db:
    image: postgres:15-alpine@sha256:620dc79c45816cff4f38f0b49c71f15a3bc6bab9439ba1eea3a76d23ebcf1e4d
    container_name: odoo-database
    hostname: odoo-database
    restart: on-failure
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
